ALTER TABLE IF EXISTS public.user_role
    ADD CONSTRAINT "fk to role_id" FOREIGN KEY (role_id)
    REFERENCES public.role (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;