ALTER TABLE IF EXISTS public.admin_shop
    ADD CONSTRAINT "fk to shop" FOREIGN KEY (shop_id)
    REFERENCES public.shop (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;