ALTER TABLE IF EXISTS public.purchase
    ADD CONSTRAINT "fk to user" FOREIGN KEY (user_id)
    REFERENCES public."user" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;